// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("4.2")]
[assembly: AssemblyFileVersion("4.2")]
[assembly: AssemblyInformationalVersion("4.2 1530f3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "4.2";
        internal const System.String AssemblyFileVersion = "4.2";
        internal const System.String AssemblyInformationalVersion = "4.2 1530f3";
    }
}
