// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("4.3.0")]
[assembly: AssemblyFileVersion("4.3.0")]
[assembly: AssemblyInformationalVersion("4.3.0 98ae06")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "4.3.0";
        internal const System.String AssemblyFileVersion = "4.3.0";
        internal const System.String AssemblyInformationalVersion = "4.3.0 98ae06";
    }
}
