// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("4.1.1")]
[assembly: AssemblyFileVersion("4.1.1")]
[assembly: AssemblyInformationalVersion("4.1.1 db15f4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "4.1.1";
        internal const System.String AssemblyFileVersion = "4.1.1";
        internal const System.String AssemblyInformationalVersion = "4.1.1 db15f4";
    }
}
